### ISSUE TITLE
PUT statement isn't working in my setup

### ISSUE THREAD

**Issue by aftermathematic** [StefanNienhuis/homebridge-programmable-http-switch#1]
I'm trying to execute a simple PUT statement to trigger a switch. So far without any luck.

this is the (local) link: http://20.20.20.20:3000/accessories/btnWebhook/buttons/hook3

All GET statements work, however when executing a PUT, I get this error: 
"Cannot PUT /accessories/btnWebhook/buttons/hook3/0"
so far I've tried .../hook3/0, .../hook3/singlePress but no success.

I have implemented the setup from the example you provided, just changed the names.

What am I doing wrong?

**My config:**
"accessories": [
                {
                    "name": "Programmable HTTP switch",
                    "identifier": "btnWebhook",
                    "buttons": [
                        {
                            "name": "btnwh1",
                            "identifier": "hook1"
                        },
                        {
                            "name": "btnwh2",
                            "identifier": "hook2",
                            "supportedActions": [
                                "singlePress",
                                "longPress"
                            ]
                        },
                        {
                            "name": "btnwh3",
                            "identifier": "hook3",
                            "supportedActions": [
                                0
                            ]
                        }
                    ]
                }
            ],
            "port": 3000,
            "platform": "ProgrammableHTTPSwitch"

**Comment by StefanNienhuis** [comment]
Hi there,

You should PUT to just /accessories/btnWebhook/buttons/hook3 with a body containing the action.

See [the README](https://github.com/StefanNienhuis/homebridge-programmable-http-switch#put-accessoriesaccessoryidentifierbuttonsbuttonidentifier) for details.

Let me know if this solves it.

**Comment by aftermathematic** [comment]
Hi there,
besides that I have no idea how to send a body with a PUT statement in C#, sadly no luck so far.
I'm testing in Postman. see screenshot. Any thoughts on what I'm doing wrong?

![put](https://user-images.githubusercontent.com/3603311/174442147-c2c7e3bf-2caa-4a3d-9444-1180bbf6e0b1.PNG)

feature request: have the action in the URL like /accessories/btnWebhook/buttons/hook3/0 or /accessories/btnWebhook/buttons/hook3/singlePress :-) :-)

**Comment by StefanNienhuis** [comment]
You need to set the Content-Type header to application/json. In Postman, you can do this with the dropdown (next to GraphQL) saying ‘Text’ and changing it to ‘JSON’.

**Comment by aftermathematic** [comment]
Thank you, this worked! I've implemented your webhook button in a private web app running on AWS to open my garagedoor. Works great!

**Comment by aftermathematic** [comment]
Just a question: I'm trying to use your plugin in the Locative app on my phone (so my garagedoor opens whenever I enter my street by car) , but Locative can only send webhooks with Post or Get. Any chance this functionality could get added?

**Comment by aftermathematic** [comment]
hello?

**Comment by StefanNienhuis** [comment]
Sorry, I will not be accommodating the plugin to all different kinds of apps. If you want, you can fork the repository.
