### ISSUE TITLE
Button Names in Home

### ISSUE THREAD

**Issue by isaiahfranco** [StefanNienhuis/homebridge-programmable-http-switch#2]
Hello,

Is there a way to have the button names show up in the Home app rather than just Button #?

![IMG_0119](https://github.com/StefanNienhuis/homebridge-programmable-http-switch/assets/41401412/2e393f39-c90a-4636-a75c-11ffb29ee654)

**Comment by StefanNienhuis** [comment]
Hi there, unfortunately this isn't customizable in HomeKit. Apple only supports setting an index.
